
"""upsert platfrom into user

Revision ID: 212496228bf8
Revises: 2ea7840639c4
Create Date: 2026-01-07 11:33:30.621914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212496228bf8'
down_revision = '2ea7840639c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quizard', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('wordly', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('arcaderush', sa.Boolean(), nullable=True))
    op.drop_column('users', 'platform')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform', mysql.ENUM('QUIZARD', 'WORDLY', 'ARCADERUSH'), nullable=True))
    op.drop_column('users', 'arcaderush')
    op.drop_column('users', 'wordly')
    op.drop_column('users', 'quizard')
    # ### end Alembic commands ###
