
"""update_enums

Revision ID: 213633e0544d
Revises: dc56a5d83762
Create Date: 2025-12-14 14:52:58.168588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '213633e0544d'
down_revision = 'dc56a5d83762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'type',
               existing_type=mysql.ENUM('DAILY', 'WEEKLY', 'MONTHLY'),
               type_=sa.Enum('STANDARD', 'PREMIUM', 'LOGIC', name='subscriptiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'type',
               existing_type=sa.Enum('STANDARD', 'PREMIUM', 'LOGIC', name='subscriptiontype'),
               type_=mysql.ENUM('DAILY', 'WEEKLY', 'MONTHLY'),
               existing_nullable=False)
    # ### end Alembic commands ###
