
"""upsert platfrom into user

Revision ID: 2ea7840639c4
Revises: f31fa3f5f448
Create Date: 2026-01-07 11:18:43.637940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ea7840639c4'
down_revision = 'f31fa3f5f448'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('platform', sa.Enum('QUIZARD', 'WORDLY', 'ARCADERUSH', name='platformtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'platform')
    # ### end Alembic commands ###
