
"""refactor quiz to played_quiz and remove quiz_ids

Revision ID: 347ecc3cfd56
Revises: 212496228bf8
Create Date: 2026-01-07 11:52:57.114007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '347ecc3cfd56'
down_revision = '212496228bf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('played_quizzes',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subs_id', sa.BigInteger(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subs_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_played_quizzes_id'), 'played_quizzes', ['id'], unique=False)
    op.drop_index(op.f('ix_quizzes_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_column('users', 'quiz_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quiz_ids', mysql.JSON(), nullable=True))
    op.create_table('quizzes',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('subs_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.Column('modified_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['subs_id'], ['subscriptions.id'], name=op.f('quizzes_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quizzes_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_quizzes_id'), 'quizzes', ['id'], unique=False)
    op.drop_index(op.f('ix_played_quizzes_id'), table_name='played_quizzes')
    op.drop_table('played_quizzes')
    # ### end Alembic commands ###
