
"""initial tables

Revision ID: 3f96cffd4914
Revises: ad6ca4b982bc
Create Date: 2026-01-13 13:19:21.197828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f96cffd4914'
down_revision = 'ad6ca4b982bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
