
"""fix_enum_time

Revision ID: 415652875aeb
Revises: 213633e0544d
Create Date: 2025-12-14 14:55:58.649089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = '415652875aeb'
down_revision = '213633e0544d'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'time',
               existing_type=mysql.ENUM('1min', '3min', '5min', '10min', '30min'),
               type_=sa.Enum('Monthly', 'Yearly', 'Lifetime', name='subscriptionlength'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'time',
               existing_type=sa.Enum('Monthly', 'Yearly', 'Lifetime', name='subscriptionlength'),
               type_=mysql.ENUM('1min', '3min', '5min', '10min', '30min'),
               existing_nullable=False)
    # ### end Alembic commands ###
