
"""add_amount_link_dates

Revision ID: 8c678786ad3c
Revises: 259f7fc7fd7f
Create Date: 2025-12-14 16:01:52.943878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c678786ad3c'
down_revision = '259f7fc7fd7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('amount', sa.Integer(), nullable=True))
    op.add_column('subscriptions', sa.Column('link', sa.String(length=512), nullable=True))
    op.add_column('user_subscribed', sa.Column('start_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_subscribed', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_subscribed', 'end_date')
    op.drop_column('user_subscribed', 'start_date')
    op.drop_column('subscriptions', 'link')
    op.drop_column('subscriptions', 'amount')
    # ### end Alembic commands ###
