
"""remove subs_id from user table

Revision ID: ad6ca4b982bc
Revises: 347ecc3cfd56
Create Date: 2026-01-07 16:05:45.242212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad6ca4b982bc'
down_revision = '347ecc3cfd56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_ibfk_2'), 'users', type_='foreignkey')
    op.drop_column('users', 'subscription_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_ibfk_2'), 'users', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
