
"""refactor_models

Revision ID: dc56a5d83762
Revises: 6f0116ab3d7a
Create Date: 2025-12-14 14:29:02.208605

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc56a5d83762'
down_revision = '6f0116ab3d7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscribed',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('subs_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subs_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscribed_id'), 'user_subscribed', ['id'], unique=False)
    op.drop_column('messages', 'sender')
    op.drop_column('messages', 'receiver')
    op.add_column('subscriptions', sa.Column('current_subs_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'current_subs_quantity')
    op.add_column('messages', sa.Column('receiver', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('messages', sa.Column('sender', mysql.VARCHAR(length=255), nullable=False))
    op.drop_index(op.f('ix_user_subscribed_id'), table_name='user_subscribed')
    op.drop_table('user_subscribed')
    # ### end Alembic commands ###
