
"""add_platform_to_subscription

Revision ID: f31fa3f5f448
Revises: fcaf78dcc1f0
Create Date: 2025-12-29 13:08:29.122904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f31fa3f5f448'
down_revision = 'fcaf78dcc1f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('platform', sa.Enum('QUIZARD', 'WORDLY', 'ARCADERUSH', name='platformtype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'platform')
    # ### end Alembic commands ###
