
"""make_fields_nullable

Revision ID: fcaf78dcc1f0
Revises: 8c678786ad3c
Create Date: 2025-12-29 12:06:43.912430

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcaf78dcc1f0'
down_revision = '8c678786ad3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscriptions', 'type',
               existing_type=mysql.ENUM('STANDARD', 'PREMIUM', 'LOGIC'),
               nullable=True)
    op.alter_column('subscriptions', 'time',
               existing_type=mysql.ENUM('MONTHLY', 'YEARLY', 'LIFETIME'),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subscriptions', 'time',
               existing_type=mysql.ENUM('MONTHLY', 'YEARLY', 'LIFETIME'),
               nullable=False)
    op.alter_column('subscriptions', 'type',
               existing_type=mysql.ENUM('STANDARD', 'PREMIUM', 'LOGIC'),
               nullable=False)
    # ### end Alembic commands ###
